# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fbebfaf4b6b03edbaf2ebe35661e770a0487d210e7ff91c261077a0e32f712ba9d3d97b0634bd4fbbae5b2ec49b0529b6bb949daac836c9d56ae5d9dd0bf1ffe

test:
  secret_key_base: 444bb017ee07984d6b144dc88970be92b088e0bb17f8af1157b7c955916b96d47a25d56cb837c1982d424440958583bfb2197b295dff1c4e26274a830db79633

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
